apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dblogapp.fullname" . }}
  labels:
    app: {{ include "dblogapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dblogapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dblogapp.name" . }}
    spec:
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name | quote }}
      {{- end }}
      containers:
        - name: dblogapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER | quote }}
            - name: DB_PASS
              value: {{ .Values.env.DB_PASS | quote }}
            - name: DB_SSLMODE
              value: {{ .Values.env.DB_SSLMODE | quote }}
            - name: SERVICE_BUS_CONNECTION_STR
              value: {{ .Values.env.SERVICE_BUS_CONNECTION_STR | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20